version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=taskmanager.settings.development
      - POSTGRES_DB=taskmanager
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=Admin255255@@      - DB_HOST=db      - DB_PORT=5433
      - REDIS_URL=redis://localhost:6380/0
      - DJANGO_SECRET_KEY=dev-secret-key
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=taskmanager
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=Admin255255@@    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser"]
      interval: 10s
      timeout: 5s
      retries: 5  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build: .
    command: celery -A taskmanager worker -l INFO
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=taskmanager.settings.development
      - POSTGRES_DB=taskmanager
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=Admin255255@@
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A taskmanager beat -l INFO
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=taskmanager.settings.development
      - POSTGRES_DB=taskmanager
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=Admin255255@@
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - db
      - redis

  flower:
    build: .
    command: celery -A taskmanager flower --port=5555
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    environment:
      - DJANGO_SETTINGS_MODULE=taskmanager.settings.development
      - POSTGRES_DB=taskmanager
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=Admin255255@@
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - celery

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local

networks:
  default:
    driver: bridge
    ipam:
      driver: default
