# Generated by Django 5.2.1 on 2025-05-12 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task')),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='TODO', help_text='Current status of the task', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', help_text='Task priority level', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(help_text='When the task is due to be completed')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to complete the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created the task', on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('visible_to', models.ManyToManyField(blank=True, help_text='Users who can view this task', related_name='visible_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('change_task_status', 'Can change task status'), ('view_all_tasks', 'Can view all tasks'), ('assign_task', 'Can assign task to users')],
                'indexes': [models.Index(fields=['status', 'due_date'], name='tasks_task_status_0eabcf_idx'), models.Index(fields=['created_by', 'status'], name='tasks_task_created_69a8b4_idx'), models.Index(fields=['assigned_to', 'status'], name='tasks_task_assigne_b3b2bc_idx')],
            },
        ),
    ]
