# Generated by Django 5.2.1 on 2025-05-13 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can see this task', related_name='visible_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
